#!/usr/bin/env python

import os
import signal
import subprocess
import sys
import argparse

# Determine the correct executable.
celery = "celery"
stdout_stderr = subprocess.Popen(["which", celery], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
stdout, stderr = stdout_stderr.communicate()
if stdout:
  pass
else:
  print >> sys.stderr, "Unable to locate celery, please install celery package"
  sys.exit(1)

subprocess.call([celery, '-A', 'pygeo.esgf.download', 'worker'], stderr=subprocess.STDOUT)
